#!/usr/bin/env python3
"""Build Writing posts from Markdown sources.

Each post lives in content/writing/<slug>.md: a front-matter block, then the
body in a small Markdown subset. This script renders writing/<slug>/index.html
and rewrites the generated parts of writing/index.html (between the NOTES
markers), writing/feed.xml and the post URLs in sitemap.xml. Then it runs
scripts/check.py. Commit the sources and the generated files together.

Front matter (one "key: value" per line; indent a line to continue a value):
  title    required
  date     required, YYYY-MM-DD
  summary  required, one or two sentences (index row, meta, feed)
  card     optional, share-card line (default: title)
  updated  optional, YYYY-MM-DD for the feed after a real revision
  linkedin optional, text for the LinkedIn teaser (default: summary)
  draft    optional, "true" skips the post

Markdown subset: paragraphs, "## " headings (numbered like the template),
"- " bullet lists, "> " blockquotes, [links](url), **strong**, *em*, `code`.

Run:
  python3 scripts/build_posts.py                    build every post
  python3 scripts/build_posts.py --linkedin <slug>  build, then print the teaser
Share cards: NODE_PATH=$(npm root -g) node brand/assets/generate.cjs
"""

import html
import json
import math
import os
import re
import shutil
import subprocess
import sys
from string import Template

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC_DIR = os.path.join(ROOT, "content", "writing")
SITE = "https://www.boutalikakis.com"
STYLE_VERSION = "6"  # keep in step with site.css?v=N on the other pages
GENERATED = "Generated by scripts/build_posts.py"
NOTES_START, NOTES_END = "<!-- NOTES:start -->", "<!-- NOTES:end -->"
REQUIRED = ("title", "date", "summary")


# --- Sources -----------------------------------------------------------------

def parse_source(path):
    with open(path, encoding="utf-8") as f:
        text = f.read()
    m = re.match(r"---\n(.*?)\n---\n(.*)\Z", text, re.S)
    if not m:
        sys.exit(f"{path}: missing front matter between --- lines")
    meta, key = {}, None
    for line in m.group(1).splitlines():
        if line[:1].isspace() and key:
            meta[key] += " " + line.strip()
        elif ":" in line:
            key, value = line.split(":", 1)
            key = key.strip()
            meta[key] = value.strip()
    for k in REQUIRED:
        if not meta.get(k):
            sys.exit(f"{path}: front matter needs '{k}'")
    for k in ("date", "updated"):
        if k in meta and not re.fullmatch(r"\d{4}-\d{2}-\d{2}", meta[k]):
            sys.exit(f"{path}: '{k}' must be YYYY-MM-DD")
    meta["slug"] = os.path.splitext(os.path.basename(path))[0]
    if not re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", meta["slug"]):
        sys.exit(f"{path}: file name must be a lowercase-hyphen slug")
    meta["body"] = m.group(2)
    return meta


def load_posts():
    posts = []
    for name in sorted(os.listdir(SRC_DIR)):
        if name.endswith(".md"):
            post = parse_source(os.path.join(SRC_DIR, name))
            if post.get("draft", "").lower() != "true":
                posts.append(post)
    # Oldest first fixes the note numbers; later lists reverse this order.
    posts.sort(key=lambda p: (p["date"], p["slug"]))
    for i, post in enumerate(posts, 1):
        post["number"] = i
    return posts


# --- Markdown subset ---------------------------------------------------------

def inline(text):
    codes = []

    def keep_code(m):
        codes.append(m.group(1))
        return f"\x00{len(codes) - 1}\x00"

    text = re.sub(r"`([^`]+)`", keep_code, text)
    text = html.escape(text, quote=False)
    text = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)",
                  lambda m: f'<a href="{m.group(2).replace(chr(34), "%22")}">{m.group(1)}</a>',
                  text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<![\w*])\*(?!\s)(.+?)(?<!\s)\*(?![\w*])", r"<em>\1</em>", text)
    return re.sub("\x00(\\d+)\x00",
                  lambda m: f"<code>{html.escape(codes[int(m.group(1))], quote=False)}</code>",
                  text)


def render_body(markdown, slug):
    out, number = [], 0
    for block in re.split(r"\n\s*\n", markdown.strip()):
        lines = [l.rstrip() for l in block.splitlines()]
        first = lines[0]
        if first.startswith("## "):
            if len(lines) > 1:
                sys.exit(f"{slug}: put a blank line after the heading '{first}'")
            number += 1
            out.append(f"<h2><span>{number}</span><span>{inline(first[3:].strip())}</span></h2>")
        elif first.startswith("#"):
            sys.exit(f"{slug}: only '## ' headings are supported ('{first}')")
        elif first.startswith("- "):
            items = []
            for line in lines:
                if line.startswith("- "):
                    items.append(line[2:].strip())
                elif items:
                    items[-1] += " " + line.strip()
            lis = "\n".join(f"  <li>{inline(i)}</li>" for i in items)
            out.append(f"<ul>\n{lis}\n</ul>")
        elif first.startswith(">"):
            quote = " ".join(l.lstrip(">").strip() for l in lines)
            out.append(f"<blockquote><p>{inline(quote)}</p></blockquote>")
        else:
            out.append(f"<p>{inline(' '.join(l.strip() for l in lines))}</p>")
    return "\n\n".join(out)


def read_minutes(markdown):
    words = len(re.findall(r"[\w'’-]+", markdown))
    return max(1, math.ceil(words / 200))


# --- Post page ---------------------------------------------------------------

PAGE = Template("""<!DOCTYPE html>
<!-- $generated from content/writing/$slug.md. Edit the Markdown, not this file. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>$title · Angelo Boutalikakis</title>
  <meta name="description" content="$summary">
  <link rel="icon" type="image/png" sizes="32x32" href="/brand/assets/favicon-32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/brand/assets/favicon-16.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/brand/assets/apple-touch-icon.png">
  <meta property="og:type" content="article">
  <meta property="og:url" content="$url">
  <meta property="og:title" content="$title">
  <meta property="og:description" content="$summary">
  <meta property="og:image" content="$site/brand/assets/og-post-$slug.png">
  <meta property="og:image:width" content="1200">
  <meta property="og:image:height" content="630">
  <meta name="twitter:card" content="summary_large_image">
  <link rel="canonical" href="$url">
  <link rel="alternate" type="application/atom+xml" title="Writing · Angelo Boutalikakis" href="/writing/feed.xml">
  <link rel="preload" href="/assets/fonts/newsreader-roman-latin-var.woff2" as="font" type="font/woff2" crossorigin>
  <link rel="stylesheet" href="../../assets/site.css?v=$style_version">
  <style>
    /* Page-local: no shared component covers a justified 64ch article body
       with numbered h2s, so this is scoped here on site.css tokens. */
    .article{max-width:64ch;margin:0 auto;font-size:18px;line-height:1.7;
      text-align:justify;hyphens:auto}
    .article > *{margin:0}
    .article > * + *{margin-top:1.15em}
    .article h2{margin:36px 0 10px;font-size:21px;font-weight:700;display:flex;
      gap:16px;text-align:left}
    .article > h2 + *{margin-top:0}
    .article ul{padding-left:1.3em}
    .article li + li{margin-top:.35em}
    .article blockquote{padding-left:20px;font-style:italic;
      border-left:var(--rule-mid) solid var(--ink)}
    .article blockquote p{margin:0}
    .article code{font-family:var(--font-mono);font-size:.8em}
    /* Justified text in a phone-width column leaves wide word gaps. */
    @media (max-width:560px){.article{text-align:left}}
  </style>
  <script type="application/ld+json">
  $jsonld
  </script>
</head>
<body>

  <a class="skip" href="#main">Skip to content</a>

  <div class="desk"><div class="sheet">

    <header class="runhead">
      <a href="/">A. Boutalikakis</a>
      <nav aria-label="Site">
        <a href="/#work">work</a>
        <a href="/about/">about</a>
        <a href="/writing/" aria-current="page">writing</a>
        <a href="/cv/">cv</a>
        <a href="https://github.com/aboutali">github</a>
      </nav>
    </header>

    <main id="main" tabindex="-1">

      <header class="titleblock" style="padding:clamp(48px,8vw,80px) 0 40px">
        <p class="kicker">Note $number</p>
        <h1 style="font-size:clamp(32px,5.4vw,50px);text-wrap:balance">$title</h1>
        <p class="mono" style="margin:16px 0 0;color:var(--graphite)">$date · $minutes min read</p>
      </header>

      <article class="article">
$body
      </article>

      <div style="max-width:64ch;margin:40px auto 0">
        <a class="mono" href="../">← All writing</a>
      </div>

    </main>

    <footer style="margin-top:72px">
      <div class="mono" style="display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap;
        font-size:12.5px;border-top:var(--rule-hair) solid var(--ink);padding-top:12px">
        <a href="/">← Home</a>
        <span style="color:var(--graphite)"><a href="https://github.com/aboutali/aboutali.github.io">Source code</a></span>
      </div>
      <p class="folio">5</p>
    </footer>

  </div></div>

</body>
</html>
""")

AUTHOR = {
    "@type": "Person", "name": "Angelo Boutalikakis", "honorificPrefix": "Dr.",
    "url": f"{SITE}/", "image": f"{SITE}/assets/headshot.jpg",
    "jobTitle": "Engagement Manager",
    "worksFor": {"@type": "Organization", "name": "McKinsey & Company"},
    "address": {"@type": "PostalAddress", "addressLocality": "Zurich", "addressCountry": "CH"},
    "sameAs": ["https://www.linkedin.com/in/angeloboutalikakis",
               "https://scholar.google.com/citations?user=4E9KeKYAAAAJ",
               "https://github.com/aboutali"],
}


def post_url(post):
    return f"{SITE}/writing/{post['slug']}/"


def render_page(post):
    url = post_url(post)
    ld = {"@context": "https://schema.org", "@type": "BlogPosting",
          "headline": post["title"], "datePublished": post["date"]}
    if "updated" in post:
        ld["dateModified"] = post["updated"]
    ld.update({"author": AUTHOR, "mainEntityOfPage": url})
    body = render_body(post["body"], post["slug"])
    body = "\n".join(("        " + l) if l else "" for l in body.splitlines())
    esc = lambda s: html.escape(s, quote=False).replace('"', "&quot;")
    return PAGE.substitute(
        generated=GENERATED, slug=post["slug"], site=SITE, url=url,
        title=esc(post["title"]), summary=esc(post["summary"]),
        number=f"{post['number']:02d}", date=post["date"],
        minutes=read_minutes(post["body"]), body=body,
        style_version=STYLE_VERSION,
        jsonld=json.dumps(ld, ensure_ascii=False, separators=(",", ":")).replace("</", "<\\/"),
    )


# --- Index, feed, sitemap ----------------------------------------------------

def render_notes(posts):
    rows = []
    for p in reversed(posts):
        rows.append(
            f'          <a href="{p["slug"]}/">\n'
            f'            <span class="t">{html.escape(p["title"], quote=False)}</span>\n'
            f'            <span class="d">{p["date"]}</span>\n'
            f'            <span class="desc">{html.escape(p["summary"], quote=False)}</span>\n'
            f'          </a>')
    return "\n".join(rows)


def update_index(text, posts):
    start, end = text.find(NOTES_START), text.find(NOTES_END)
    if start < 0 or end < start:
        sys.exit(f"writing/index.html: missing {NOTES_START} / {NOTES_END} markers")
    return text[:start + len(NOTES_START)] + "\n" + render_notes(posts) + "\n          " + text[end:]


def render_feed(posts):
    x = lambda s: html.escape(s, quote=False)
    stamp = lambda d: f"{d}T00:00:00Z"
    newest = max((p.get("updated", p["date"]) for p in posts), default="2026-07-02")
    entries = "".join(
        "  <entry>\n"
        f"    <title>{x(p['title'])}</title>\n"
        f'    <link href="{post_url(p)}"/>\n'
        f"    <id>{post_url(p)}</id>\n"
        f"    <published>{stamp(p['date'])}</published>\n"
        f"    <updated>{stamp(p.get('updated', p['date']))}</updated>\n"
        f"    <summary>{x(p['summary'])}</summary>\n"
        "  </entry>\n"
        for p in reversed(posts))
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f"<!-- {GENERATED} from content/writing/. Edit the Markdown, not this file. -->\n"
        '<feed xmlns="http://www.w3.org/2005/Atom">\n'
        "  <title>Writing · Angelo Boutalikakis</title>\n"
        "  <subtitle>Research, publications, and notes by Angelo Boutalikakis.</subtitle>\n"
        f'  <link href="{SITE}/writing/feed.xml" rel="self"/>\n'
        f'  <link href="{SITE}/writing/"/>\n'
        f"  <id>{SITE}/writing/</id>\n"
        f"  <updated>{stamp(newest)}</updated>\n"
        f"  <author><name>Angelo Boutalikakis</name><uri>{SITE}/</uri></author>\n"
        f"{entries}"
        "</feed>\n")


def update_sitemap(text, posts):
    post_line = re.compile(r"^\s*<url><loc>" + re.escape(SITE) + r"/writing/[^<]+/</loc></url>\n", re.M)
    text = post_line.sub("", text)
    anchor = f"  <url><loc>{SITE}/writing/</loc></url>\n"
    if anchor not in text:
        sys.exit("sitemap.xml: missing the /writing/ entry")
    lines = "".join(f"  <url><loc>{post_url(p)}</loc></url>\n" for p in reversed(posts))
    return text.replace(anchor, anchor + lines, 1)


# --- Main --------------------------------------------------------------------

def write_if_changed(relpath, content):
    path = os.path.join(ROOT, relpath)
    try:
        with open(path, encoding="utf-8") as f:
            if f.read() == content:
                return
    except FileNotFoundError:
        os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"wrote {relpath}")


def read(relpath):
    with open(os.path.join(ROOT, relpath), encoding="utf-8") as f:
        return f.read()


def remove_orphans(posts):
    """Delete generated post folders whose Markdown source is gone."""
    slugs = {p["slug"] for p in posts}
    writing = os.path.join(ROOT, "writing")
    for name in sorted(os.listdir(writing)):
        page = os.path.join(writing, name, "index.html")
        if name in slugs or not os.path.isfile(page):
            continue
        with open(page, encoding="utf-8") as f:
            if GENERATED in f.read(300):
                shutil.rmtree(os.path.join(writing, name))
                print(f"removed writing/{name}/ (no source)")


def linkedin_teaser(posts, slug):
    post = next((p for p in posts if p["slug"] == slug), None)
    if not post:
        sys.exit(f"--linkedin: no published post '{slug}'")
    text = post.get("linkedin") or post["summary"]
    return f"{text}\n\n{post_url(post)}"


def main(argv):
    slug = None
    if argv[:1] == ["--linkedin"] and len(argv) == 2:
        slug = argv[1]
    elif argv:
        sys.exit(__doc__)
    posts = load_posts()
    for post in posts:
        write_if_changed(f"writing/{post['slug']}/index.html", render_page(post))
    remove_orphans(posts)
    write_if_changed("writing/index.html", update_index(read("writing/index.html"), posts))
    write_if_changed("writing/feed.xml", render_feed(posts))
    write_if_changed("sitemap.xml", update_sitemap(read("sitemap.xml"), posts))
    code = subprocess.call([sys.executable, os.path.join(ROOT, "scripts", "check.py")])
    if slug:
        print("\n--- LinkedIn post (paste as a native post) ---\n")
        print(linkedin_teaser(posts, slug))
    return code


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
